academy_dbt_test:
  target: dev  # ambiente padrão
  outputs:
    # Ambiente de desenvolvimento 
    dev:
      type: bigquery
      method: service-account
      project: academy-dbt-test
      dataset: academy_dbt_prod 
      keyfile: temp/academy-dbt-test-6eda8ac0ab9a.json  
      location: US 

